/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import bankmanagementsystem.Register;
import bankmanagementsystem.StorageManager;
import bankmanagementsystem.User;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author wfati
 */
public class NewAccount extends javax.swing.JFrame {
    //private Object timeStamp;
    Register reg = new Register();
    User user = new User();
    /**
     * Creates new form NewAccount
     */
    public NewAccount() {
        initComponents();
       //displayData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public static String FirstName="";
    public static String LastName="";
//    public static String DOB = "";
//    public static String CNIC="";
//    public static String MobileNo="";
    public static String City="";
    public static double initialBalance=0.0;
    public static String PINcode="";
    public static String UserAccno="";
//    public static String Gender="";
//    public static String Address="";
    public static String AccType="";
    public static String BranchCode="";
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Firstname = new javax.swing.JTextField();
        Lastname = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Lcity = new javax.swing.JLabel();
        city = new javax.swing.JComboBox();
        accType = new javax.swing.JLabel();
        Lpincode = new javax.swing.JLabel();
        pincode = new javax.swing.JPasswordField();
        reset = new javax.swing.JButton();
        acctype = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        accbalance = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        Firstname.setBackground(new java.awt.Color(0, 0, 0));
        Firstname.setForeground(new java.awt.Color(255, 255, 255));
        Firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnameActionPerformed(evt);
            }
        });

        Lastname.setBackground(new java.awt.Color(0, 0, 0));
        Lastname.setForeground(new java.awt.Color(255, 255, 255));

        register.setBackground(new java.awt.Color(0, 0, 0));
        register.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name ");

        jLabel2.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name");

        Lcity.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Lcity.setForeground(new java.awt.Color(255, 255, 255));
        Lcity.setText("City");

        city.setBackground(new java.awt.Color(0, 0, 0));
        city.setForeground(new java.awt.Color(102, 102, 102));
        city.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Karachi", "Hyderabad ", "Faisalabad ", "Bhawalpur ", "Lahore ", "Islamabad ", "Peshawar ", "Quetta ", "Nawabshah ", "Sukkur ", "Multan", " " }));
        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });

        accType.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        accType.setForeground(new java.awt.Color(255, 255, 255));
        accType.setText("Account Type");

        Lpincode.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Lpincode.setForeground(new java.awt.Color(255, 255, 255));
        Lpincode.setText("Pin Code");

        pincode.setBackground(new java.awt.Color(0, 0, 0));
        pincode.setForeground(new java.awt.Color(255, 255, 255));

        reset.setBackground(new java.awt.Color(0, 0, 0));
        reset.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        acctype.setBackground(new java.awt.Color(0, 0, 0));
        acctype.setForeground(new java.awt.Color(102, 102, 102));
        acctype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Current", "Savings" }));
        acctype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acctypeActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Registration Form");

        balance.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        balance.setForeground(new java.awt.Color(255, 255, 255));
        balance.setText("Initial Deposit");

        accbalance.setBackground(new java.awt.Color(0, 0, 0));
        accbalance.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Lcity)
                    .addComponent(Lpincode, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accType)
                    .addComponent(balance))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(register))
                    .addComponent(pincode, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acctype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lcity)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acctype, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accType))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balance)
                    .addComponent(accbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lpincode, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pincode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static void writeObjectToFile(User obj, File file) throws IOException {
        try (FileOutputStream fos = new FileOutputStream(file);
             ObjectOutputStream oos = new ObjectOutputStream(fos)) {
            oos.writeObject(obj);
            oos.flush();
        } 
    }
    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
     public void displayData(){
         //String[] displayAccountTypes = StorageManager.getInstance().getAccountTypes();
         //acctype.setModel(new javax.swing.DefaultComboBoxModel<>(displayAccountTypes));
     }
    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
         String selected =city.getSelectedItem().toString();
         City = selected;
         String code="0000";
        try {
      File myObj = new File("branchCity.txt");
      Scanner myReader = new Scanner(myObj);
      while (myReader.hasNextLine()) {
        String data = myReader.nextLine();
        String[] parts = data.split(",");
        if(parts.length==2&&parts[1].equals(City))
            code=parts[0];
        BranchCode=code;
      }
      myReader.close();
    } catch (FileNotFoundException e) {
      System.out.println("An error occurred.");
      e.printStackTrace();
         //UserAccno=reg.generateAccountNumber(City,AccType);
    }//BranchCode=code;
    }//GEN-LAST:event_cityActionPerformed
  
    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        FirstName = Firstname.getText().toString();
        user.setFirstName(FirstName);
        LastName = Lastname.getText().toString();
        user.setLastName(LastName);
        //DOB = (String) Date.getSelectedItem() + "/" + (String) Month.getSelectedItem() + "/" + (String) Year.getSelectedItem() + "\n";
        //user.setDateOfBirth(DOB);
        //Gender = gnder.getSelectedItem().toString();
        //user.setGender(Gender);
        //MobileNo = mobileno.getText().toString();
        //user.setContactNumber(MobileNo);
        //CNIC = cnic.getText().toString();
        //user.setCNIC(cnic.getText().toString());
        //Address = address.getText().toString();
       // user.setAddress(Address);
        PINcode = pincode.getText().toString();
        user.setPincode(PINcode);
        AccType=acctype.getSelectedItem().toString();
        user.setAccountType(AccType);
        UserAccno = reg.generateAccountNumber(City,BranchCode,AccType);
        user.setAccountNumber(UserAccno);
        
        PINcode = pincode.getText().toString();
        user.setPincode(PINcode);
        initialBalance = Double.parseDouble(accbalance.getText());
        
        //Address = address.getText().toString();
        //user.setAddress(Address);
        User user2 =new User(UserAccno,PINcode,FirstName, LastName, initialBalance);
        try {
            StorageManager.getInstance().addUser(user2);
        } catch (Exception ex) {
            Logger.getLogger(NewAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
        //City = (String) city.getSelectedItem();
        //UserAccno=reg.generateAccountNumber(city.getSelectedItem().toString());
        //Database
//        String file = UserAccno + ".txt";
//        File log = new File(file);//name of file
//        try {
//             if (log.exists() == false) {
//                System.out.println("We had to make a new file.");
//                log.createNewFile();
//                 
//             }
//             PrintWriter out = new PrintWriter(new FileWriter(log, true));
//             out.append(user.getAccountNumber());
//            //writeObjectToFile(user,log);
//        } catch (IOException ex) {
//            Logger.getLogger(NewAccount.class.getName()).log(Level.SEVERE, null, ex);
//        }
        /*try {
            if (log.exists() == false) {
                System.out.println("We had to make a new file.");
                log.createNewFile();
            } else {
                UserAccno = reg.generateAccountNumber(City);
                file = UserAccno + ".txt";
                log = new File(file);
                log.createNewFile();
            }
            try (PrintWriter out = new PrintWriter(new FileWriter(log, true))) {
                out.append(UserAccno + "\t" + pincode.getText() + "\t" + Firstname.getText() + "\t" + Lastname.getText() + "\t" + "\t" + DOB + "\t" + gnder.getSelectedItem() + "\t" + mobileno.getText() + "\t" + cnic.getText() + "\t" + city.getSelectedItem() + "\t" + acctype.getSelectedItem() + "\t" + address.getText());
                out.close();
            }
        } catch (IOException e) {
            System.out.println("COULD NOT LOG!!");
        }*/
        //Account Number file
        File acclog = new File("AccountNo.txt");
        try {
            if (acclog.exists() == false) {
                System.out.println("We had to make a new file of account.");
                acclog.createNewFile();
            }
            try (PrintWriter out2 = new PrintWriter(new FileWriter(acclog, true))) {
                out2.append("\n" + UserAccno + "\t\t" + pincode.getText());
                out2.close();
            }
        } catch (IOException e) {
            System.out.println("COULD NOT ACCLOG!!");
        }

        if (FirstName.equals("")) {
            JOptionPane.showMessageDialog(null, "FirstName is Mandatory");
        } else if (LastName.equals("")) {
            JOptionPane.showMessageDialog(null, "LastName is Mandatory");
//        } else if (CNIC.equals("")) {
//            JOptionPane.showMessageDialog(null, "CNIC is Mandatory");
//        } else if (CNIC.length() != 13) {
//            JOptionPane.showMessageDialog(null, "CNIC must be 13 digits");
//        } else if (MobileNo.equals("")) {
//            JOptionPane.showMessageDialog(null, "Mobile Number is Mandatory");
//        } else if (MobileNo.length() != 11) {
//            JOptionPane.showMessageDialog(null, "Mobile Number must be 11 digits");
        } else if (PINcode.equals("")) {
            JOptionPane.showMessageDialog(null, "PIN is Mandatory");
        } else if (PINcode.length() != 4) {
            JOptionPane.showMessageDialog(null, "PIN must be 4 digits");
        } else {
            //close();
            this.setVisible(false);
             JOptionPane.showMessageDialog(null, "Account Successfully Created!");
            new HomePage().setVisible(true);
            
        }

    }//GEN-LAST:event_registerActionPerformed

    private void FirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:         
        Firstname.setText(null);
        Lastname.setText(null);
//        mobileno.setText(null);
//        cnic.setText(null);
        pincode.setText(null);
//        Date.setSelectedIndex(0);
//        Month.setSelectedIndex(0);
//        Year.setSelectedIndex(0);
        city.setSelectedIndex(0);
//        address.setText(null);
//        gnder.setSelectedIndex(0);
        acctype.setSelectedIndex(0);


    }//GEN-LAST:event_resetActionPerformed

    private void acctypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acctypeActionPerformed
    // TODO add your handling code here:
        if(acctype.getSelectedItem().toString().equals("Current"))
            reg.typecode="00";
        else if(acctype.getSelectedItem().toString().equals("Savings"))
                reg.typecode="01";
        else{
         System.out.println("Choose an appropriate account type.");
    }//GEN-LAST:event_acctypeActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Firstname;
    private javax.swing.JTextField Lastname;
    private javax.swing.JLabel Lcity;
    private javax.swing.JLabel Lpincode;
    private javax.swing.JLabel accType;
    private javax.swing.JTextField accbalance;
    private javax.swing.JComboBox acctype;
    private javax.swing.JLabel balance;
    private javax.swing.JComboBox city;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pincode;
    private javax.swing.JButton register;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
