/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import bankmanagementsystem.StorageManager;
import bankmanagementsystem.Transaction;
import bankmanagementsystem.User;
import loantree.JFrame1;
/**
 *
 * @author madih
 */
public class UserPage extends javax.swing.JFrame {

    /**
     * Creates new form UserPage
     */
    public UserPage() {
        initComponents();
                displayData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        transactionReportBtn = new javax.swing.JButton();
        applyForLoanBtn = new javax.swing.JButton();
        atmBtn = new javax.swing.JButton();
        showAccountNumber = new javax.swing.JLabel();
        firstNameField = new javax.swing.JLabel();
        lastNameField = new javax.swing.JLabel();
        accountBalanceField = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        signOutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Account Number");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("First Name");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Account Balance");

        transactionReportBtn.setBackground(new java.awt.Color(0, 0, 0));
        transactionReportBtn.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        transactionReportBtn.setForeground(new java.awt.Color(255, 255, 255));
        transactionReportBtn.setText("Transaction Report");
        transactionReportBtn.setBorderPainted(false);
        transactionReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionReportBtnActionPerformed(evt);
            }
        });

        applyForLoanBtn.setBackground(new java.awt.Color(0, 0, 0));
        applyForLoanBtn.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        applyForLoanBtn.setForeground(new java.awt.Color(255, 255, 255));
        applyForLoanBtn.setText("Apply for Loan");
        applyForLoanBtn.setBorderPainted(false);
        applyForLoanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyForLoanBtnActionPerformed(evt);
            }
        });

        atmBtn.setBackground(new java.awt.Color(0, 0, 0));
        atmBtn.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        atmBtn.setForeground(new java.awt.Color(255, 255, 255));
        atmBtn.setText("ATM");
        atmBtn.setBorderPainted(false);
        atmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atmBtnActionPerformed(evt);
            }
        });

        showAccountNumber.setForeground(new java.awt.Color(255, 255, 255));
        showAccountNumber.setText("jLabel3");

        firstNameField.setForeground(new java.awt.Color(255, 255, 255));
        firstNameField.setText("jLabel3");

        lastNameField.setForeground(new java.awt.Color(255, 255, 255));
        lastNameField.setText("jLabel5");

        accountBalanceField.setForeground(new java.awt.Color(255, 255, 255));
        accountBalanceField.setText("jLabel6");

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User");

        signOutBtn.setBackground(new java.awt.Color(0, 0, 0));
        signOutBtn.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        signOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        signOutBtn.setText("Sign Out");
        signOutBtn.setBorderPainted(false);
        signOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(firstNameField))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastNameField))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(accountBalanceField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(175, 175, 175))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(92, 92, 92)
                .addComponent(signOutBtn)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(atmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applyForLoanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transactionReportBtn))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(signOutBtn)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(showAccountNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(firstNameField))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastNameField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountBalanceField)
                    .addComponent(jLabel5))
                .addGap(35, 35, 35)
                .addComponent(transactionReportBtn)
                .addGap(18, 18, 18)
                .addComponent(applyForLoanBtn)
                .addGap(18, 18, 18)
                .addComponent(atmBtn)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transactionReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionReportBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ViewTransaction().setVisible(true);
    }//GEN-LAST:event_transactionReportBtnActionPerformed

    private void atmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atmBtnActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        new ATMPage().setVisible(true);
    }//GEN-LAST:event_atmBtnActionPerformed

    private void signOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutBtnActionPerformed
        // TODO add your handling code here:
        StorageManager.setCurrentUser(null);
        this.setVisible(false);
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_signOutBtnActionPerformed

    private void applyForLoanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyForLoanBtnActionPerformed
     new JFrame1().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_applyForLoanBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public void displayData(){
        User user = StorageManager.getCurrentUser();
        if(user != null){
//            user.addTransaction(new Transaction("deposit", 12, "12/12/12", "It is for testing purpose"));
            showAccountNumber.setText(user.getAccountNumber());
            firstNameField.setText(user.getFirstName());
            lastNameField.setText(user.getLastName());
            accountBalanceField.setText(Double.toString(user.getAccountBalance()));
        }
        else{
            System.out.println("user was null");
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountBalanceField;
    private javax.swing.JButton applyForLoanBtn;
    private javax.swing.JButton atmBtn;
    private javax.swing.JLabel firstNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastNameField;
    private javax.swing.JLabel showAccountNumber;
    private javax.swing.JButton signOutBtn;
    private javax.swing.JButton transactionReportBtn;
    // End of variables declaration//GEN-END:variables
}
