/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import bankmanagementsystem.StorageManager;
import bankmanagementsystem.User;
import bankmanagementsystem.Transaction;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author madih
 */
public class ViewTransaction extends javax.swing.JFrame {
    ArrayList<Transaction> displayedTransactions;
    /**
     * Creates new form ViewTransaction
     */
    public ViewTransaction() {
        initComponents();
        displayData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        returnHomeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        returnHomeBtn.setBackground(new java.awt.Color(0, 0, 0));
        returnHomeBtn.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        returnHomeBtn.setForeground(new java.awt.Color(255, 255, 255));
        returnHomeBtn.setText("Return to Home page");
        returnHomeBtn.setBorderPainted(false);
        returnHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnHomeBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.setBorderPainted(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        transactionTable.setBackground(new java.awt.Color(0, 0, 0));
        transactionTable.setForeground(new java.awt.Color(255, 255, 255));
        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(transactionTable);

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Transaction Report");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel1)
                        .addGap(0, 262, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addGap(88, 88, 88))
                            .addComponent(returnHomeBtn, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(returnHomeBtn)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new UserPage().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void returnHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnHomeBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_returnHomeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public void displayData() {
//        User user = StorageManager.getCurrentUser();
//        if (user != null) {
//            ArrayList<Transaction> transactionData = user.getTransaction();
//            System.out.println("current transaction" + transactionData.isEmpty());
//            if (transactionData != null) {
//                String serialNumberConcatenate = "";
//                String dateConcatenate = "";
//                String transactionTypeConcatenate = "";
//                String amountConcatenate = "";
//                String descriptionConcatenate = "";
//                for (int i = transactionData.size()-1; i >= 0; i--) {
//                    System.out.println("current transaction" + transactionData.get(i));
//                    serialNumberConcatenate += i + "\n";
//                    dateConcatenate += transactionData.get(i).getDate()+ " \n";
//                    transactionTypeConcatenate += transactionData.get(i).getTransactionType() + " \n";
//                    amountConcatenate += Math.abs(transactionData.get(i).getAmount()) + " \n";
//                    descriptionConcatenate += transactionData.get(i).getDescription() + " \n";
//                    
//                }
//                serialNumberField.setText(serialNumberConcatenate);
//                dateField.setText(dateConcatenate);
//                transactionTypeField.setText(transactionTypeConcatenate);
//                amountField.setText(amountConcatenate);
//                descriptionField.setText(descriptionConcatenate);
//            }
//        } else {
////            popup error
//            System.out.println("user is null");
//        }
//    }
    
    public void displayData(){
        try {
//            String[] titles = {"Account Number", "Branch", "Account Type", "First Name", "Last Name", "Balance"};
            displayedTransactions = StorageManager.getCurrentUser().getTransaction();
//            2D array of String size=displayedUser.size()
//for loop insert in rows elements = 
            printTable(displayedTransactions);
        } catch (Exception ex) {
            Logger.getLogger(DisplayUserReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
public void printTable(ArrayList<Transaction> displayedTransactions){
    String[][] displayGrid = new String[displayedTransactions.size()][6];
            for(int i = 0; i<displayedTransactions.size(); i++){
                displayGrid[i] = displayedTransactions.get(i).getDisplayRow();
            }
            transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            displayGrid,
            new String [] {
                "Date", "Transaction Type", "Amount", "Description"
            }
        ));
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton returnHomeBtn;
    private javax.swing.JTable transactionTable;
    // End of variables declaration//GEN-END:variables
}
